### ISSUE TITLE
App not responding when clicking "Print" button

### ISSUE THREAD

**Issue by dancromwell** [alliance-pcsg/orbis-label-printer#3]
We have staff at three of our Network Zone institutions all reporting an issue using the Orbis Cascade Label Printer.   They report that after navigating to an individual item it displays in the preview pane of the app but when clicking "Print" nothing happens.   This behavior evidently began over the weekend of 3/4/2023 as we got three separate reports on Monday 3/6/2023.   I have no idea if this is only a local thing that we are seeing in our environment only.   Don't know where to start to troubleshoot.   I have tested myself using Chrome and Microsoft Edge and replicated the reported behavior in that when clicking "Print" on the preview pane nothing happens.  No label is printed.  I tested printing with SpineOMatic and was able to print to my connected printer.

Daniel Cromwell

**Comment by tmarnell** [comment]
Thanks for reporting, Daniel! The March maintenance release also took place this weekend starting 3/5 at 8:00 UTC, so it's likely a change in Alma now prevents the print window from opening. Chrome's console says, "Blocked opening '' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set."

@jweisman Josh, is this something that can be quickly corrected, or is the window.open() method no longer viable? The trouble seems to start at [main.component.ts, line 178](https://github.com/alliance-pcsg/orbis-label-printer/blob/545ae90f7e3d397c6b8efb9e54e7b640bd435c4c/cloudapp/src/app/main/main.component.ts#L178).

**Comment by dancromwell** [comment]
@tmarnell thanks for your attention to this issue.  We appreciate it much.

Daniel

**Comment by wclpll** [comment]
We are experiencing exactly the same issue here in my library. Orbis app "Print" button doesn't respond. 
Linda Wen
AU_Law
WRLC

**Comment by d22** [comment]
Hi @tmarnell 
It seems as if your `manifest.json` is missing the `contentSecurity` configuration which is needed to open popup windows.
You need to add something like this to `manifest.json`

```json
"contentSecurity": {
      "sandbox": {
         "popups": true      
      }
}
```
See the documentation: https://developers.exlibrisgroup.com/cloudapps/docs/manifest/
BR
Jonas

**Comment by dancromwell** [comment]
@tmarnell I'm getting reports that the app is printing again.  Did someone do something on your end to fix it?  If so it is much appreciated.

Daniel

**Comment by tmarnell** [comment]
@dancromwell I'm away at a multi-day meeting and wasn't able to make any changes! But the print button is working again in my quick tests too, which is great. I'll do some more testing across browsers when I'm back next week.

**Comment by ori229** [comment]
As noted by @d22 please add contentSecurity to manifest.json
I'm sorry I missed this thread here, and that I'm only updating here now.
We made a change on Alma's side so that the app will work.  This is why it started to work again 3 days ago. But if you'll make a change to the app in the future our change will get overridden, so it will be great if you could update manifest.json and commit  (no need for a new Release).
We still don't know yet why the app worked before March Release without allowing popups in contentSecurity, but it is by design that it should allow popups only if configured to.
Thanks,
Ori
Alma Dev. 
Ex Libris

**Comment by tmarnell** [comment]
Thanks, @d22 and @ori229! I've added the contentSecurity section to manifest.json in commit 00812a6.
